Models/ViewModels/GraduatingClass/CreateGraduatingClassViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminMNS.WebApp.Models.ViewModel.GraduatingClass
{
    public class CreateGraduatingClassViewModel
	{
        [Required(ErrorMessage = "Le nom de la classe est obligatoire"), Display(Name = "Nom de la formation")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "La date de début de formation est obligatoire"), DataType(DataType.Date), Display(Name = "Date de début de formation")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "La date de fin de formation est obligatoire"), DataType(DataType.Date), Display(Name = "Date de fin de formation")]
        public DateTime EndDate { get; set; }
	}
}

Models/ViewModels/GraduatingClass/DeleteGraduatingClassViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminMNS.WebApp.Models.ViewModel.GraduatingClass
{
    public class DeleteGraduatingClassViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Nom")]
        public string? Name { get; set; }

        [Display(Name = "Date de début"), DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        [Display(Name = "Date de fin"), DataType(DataType.Date)]
        public DateTime EndDate { get; set; }

        public DeleteGraduatingClassViewModel()
        {
            
        }

        public DeleteGraduatingClassViewModel(Data.Entities.GraduatingClass graduatingClass)
        {
            Id = graduatingClass.Id;
            Name = graduatingClass.Name;
            StartDate = graduatingClass.StartDate;
            EndDate = graduatingClass.EndDate;
        }
    }
}

Models/ViewModels/GraduatingClass/DetailsGraduatingClassViewModel.cs
using AdminMNS.WebApp.Data.Entities;
using NuGet.ProjectModel;
using System.ComponentModel.DataAnnotations;

namespace AdminMNS.WebApp.Models.ViewModel.GraduatingClass
{
	public class DetailsGraduatingClassViewModel
	{
		public int Id { get; set; }

		[Display(Name = "Nom")]
		public string? Name { get; set; }

		[Display(Name = "Date de début"), DataType(DataType.Date)]
		public DateTime StartDate { get; set; }

		[Display(Name = "Date de fin"), DataType(DataType.Date)]
		public DateTime EndDate { get; set; }

        public DetailsGraduatingClassViewModel()
        {
            
        }

        public DetailsGraduatingClassViewModel(Data.Entities.GraduatingClass graduatingClass)
		{
			Id = graduatingClass.Id;
			Name = graduatingClass.Name;
			StartDate = graduatingClass.StartDate;
			EndDate = graduatingClass.EndDate;
		}
    }
}

Models/ViewModels/GraduatingClass/EditGraduatingClassViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminMNS.WebApp.Models.ViewModel.GraduatingClass
{
	public class EditGraduatingClassViewModel
	{
		[Required]
		public int Id { get; set; }

		[Display(Name = "Nom")]
		public string? Name { get; set; }

		[Display(Name = "Date de début"), DataType(DataType.Date)]
		public DateTime StartDate { get; set; }

		[Display(Name = "Date de fin"), DataType(DataType.Date)]
		public DateTime EndDate { get; set; }

        public EditGraduatingClassViewModel()
        {
            
        }

        public EditGraduatingClassViewModel(Data.Entities.GraduatingClass graduatingClass)
		{
			Id = graduatingClass.Id;
			Name = graduatingClass.Name;
			StartDate = graduatingClass.StartDate;
			EndDate = graduatingClass.EndDate;
		}
    }
}

Models/ViewModels/GraduatingClass/IndexGraduatingClassViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminMNS.WebApp.Models.ViewModel.GraduatingClass
{
	public class IndexGraduatingClassViewModel
	{
		public int Id { get; set; }

		[Display(Name = "Nom")]
		public string? Name { get; set; }

		[Display(Name = "Date de début"), DataType(DataType.Date)]
		public DateTime StartDate { get; set; }

		[Display(Name = "Date de fin"), DataType(DataType.Date)]
		public DateTime EndDate { get; set; }

        public IndexGraduatingClassViewModel()
        {
            
        }

        public IndexGraduatingClassViewModel(Data.Entities.GraduatingClass graduatingClass)
		{
			Id = graduatingClass.Id;
			Name = graduatingClass.Name;
			StartDate = graduatingClass.StartDate;
			EndDate = graduatingClass.EndDate;
		}
    }
}

Controllers/AdministrationController.cs
using AdminMNS.WebApp.App_Code.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AdminMNS.WebApp.Controllers
{
	[Authorize(Roles = $"{Roles.Admin}, {Roles.Personnel}")]
	public class AdministrationController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Controllers/GraduatingClassController.cs
using AdminMNS.WebApp.App_Code.Helpers;
using AdminMNS.WebApp.Data;
using AdminMNS.WebApp.Data.Entities;
using AdminMNS.WebApp.Models.ViewModel.GraduatingClass;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminMNS.WebApp.Controllers
{
	[Authorize(Roles = Roles.Admin)]
	public class GraduatingClassController : Controller
	{
		private readonly AppDbContext _context;

		public GraduatingClassController(AppDbContext context)
		{
			_context = context;
		}

		public async Task<IActionResult> Index()
		{
			return _context.GraduatingClass != null ?
						View(await _context.GraduatingClass.Select(gc => new IndexGraduatingClassViewModel(gc)).ToListAsync()) :
						Problem("Entity set 'AppDbContext.GraduatingClass'  is null.");
		}

		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.GraduatingClass == null)
			{
				return NotFound();
			}

			var graduatingClass = await _context.GraduatingClass
				.FirstOrDefaultAsync(m => m.Id == id);
			if (graduatingClass == null)
			{
				return NotFound();
			}

			DetailsGraduatingClassViewModel model = new DetailsGraduatingClassViewModel(graduatingClass);

			return View(model);
		}

		public IActionResult Create()
		{
			CreateGraduatingClassViewModel model = new CreateGraduatingClassViewModel();

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,StartDate,EndDate")] GraduatingClass graduatingClass)
		{
			if (ModelState.IsValid)
			{
				_context.Add(graduatingClass);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(graduatingClass);
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.GraduatingClass == null)
			{
				return NotFound();
			}

			GraduatingClass? graduatingClass = await _context.GraduatingClass.FindAsync(id);
			if (graduatingClass == null)
			{
				return NotFound();
			}

			EditGraduatingClassViewModel model = new EditGraduatingClassViewModel(graduatingClass);

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, GraduatingClass graduatingClass)
		{
			if (id != graduatingClass.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(graduatingClass);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					return NotFound();
				}
				return RedirectToAction(nameof(Index));
			}
			return View(graduatingClass);
		}

		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.GraduatingClass == null)
			{
				return NotFound();
			}

			var graduatingClass = await _context.GraduatingClass
				.FirstOrDefaultAsync(m => m.Id == id);
			if (graduatingClass == null)
			{
				return NotFound();
			}

			DeleteGraduatingClassViewModel model = new DeleteGraduatingClassViewModel(graduatingClass);

			return View(model);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.GraduatingClass == null)
			{
				return Problem("Entity set 'AppDbContext.GraduatingClass'  is null.");
			}
			GraduatingClass? graduatingClass = await _context.GraduatingClass.FindAsync(id);
			if (graduatingClass != null)
			{
				_context.GraduatingClass.Remove(graduatingClass);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool GraduatingClassExists(int id)
		{
			return (_context.GraduatingClass?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Views/GraduatingClass/Create.cshtml
@model AdminMNS.WebApp.Models.ViewModel.GraduatingClass.CreateGraduatingClassViewModel

@{
	ViewData["Title"] = "Ajouter Formation";
}

<div class="container-menu">
	<h1>Ajouter</h1>

	<h4>Formation</h4>
	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="Create">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="Name" class="control-label"></label>
					<input asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="StartDate" class="control-label"></label>
					<input asp-for="StartDate" class="form-control" />
					<span asp-validation-for="StartDate" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="EndDate" class="control-label"></label>
					<input asp-for="EndDate" class="form-control" />
					<span asp-validation-for="EndDate" class="text-danger"></span>
				</div>
				<div class="form-group">
					<input type="submit" value="Ajouter" class="btn" />
				</div>
			</form>
		</div>
	</div>

	<div>
		<a asp-controller="Administration" asp-action="Index">Retour à l'accueil d'administration</a> |
		<a asp-action="Index">Retour à la liste</a>
	</div>
</div>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Views/GraduatingClass/Delete.cshtml
@model AdminMNS.WebApp.Models.ViewModel.GraduatingClass.DeleteGraduatingClassViewModel

@{
	ViewData["Title"] = "Supprimer Formation";
}

<div class="container-menu">
	<h1>Supprimer</h1>

	<h4 class="text-danger">Voulez-vous vraiment supprimer cette formation ?</h4>
	<div>
		<hr />
		<dl class="row">
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Name)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Name)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.StartDate)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.StartDate)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.EndDate)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.EndDate)
			</dd>
		</dl>

		<form asp-action="Delete">
			<input type="hidden" asp-for="Id" />
			<input type="submit" value="Delete" class="btn" /> |
			<a asp-action="Index">Retour à la liste</a>
		</form>
	</div>
</div>

Views/GraduatingClass/Details.cshtml
@model AdminMNS.WebApp.Models.ViewModel.GraduatingClass.DetailsGraduatingClassViewModel

@{
	ViewData["Title"] = "Détails Formation";
}

<div class="container-menu">
	<h1>Détails</h1>

	<div>
		<h4>Formation</h4>
		<hr />
		<dl class="row">
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Name)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Name)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.StartDate)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.StartDate)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.EndDate)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.EndDate)
			</dd>
		</dl>
	</div>
	<div>
		<a asp-action="Edit" asp-route-id="@Model?.Id">Éditer</a> |
		<a asp-action="Index">Retour à la liste</a>
	</div>
</div>

Views/GraduatingClass/Edit.cshtml
@model AdminMNS.WebApp.Models.ViewModel.GraduatingClass.EditGraduatingClassViewModel

@{
	ViewData["Title"] = "Éditer Formation";
}

<div class="container-menu">
	<h1>Éditer</h1>

	<h4>Formation</h4>
	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="Edit">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="Id" />
				<div class="form-group">
					<label asp-for="Name" class="control-label"></label>
					<input asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="StartDate" class="control-label"></label>
					<input asp-for="StartDate" class="form-control" />
					<span asp-validation-for="StartDate" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="EndDate" class="control-label"></label>
					<input asp-for="EndDate" class="form-control" />
					<span asp-validation-for="EndDate" class="text-danger"></span>
				</div>
				<div class="form-group">
					<input type="submit" value="Sauvegarder" class="btn" />
				</div>
			</form>
		</div>
	</div>

	<div>
		<a asp-action="Index">Retour à la liste</a>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Views/GraduatingClass/Index.cshtml
@model IEnumerable<AdminMNS.WebApp.Models.ViewModel.GraduatingClass.IndexGraduatingClassViewModel>

@{
	ViewData["Title"] = "Index Formation";
}

<div class="container-menu">
	<h1>Index</h1>

	<p>
		<a asp-action="Create">Ajouter une nouvelle formation</a>
	</p>
	<table class="table">
		<thead>
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.Name)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.StartDate)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.EndDate)
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Name)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.StartDate)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.EndDate)
					</td>
					<td>
						<a asp-action="Edit" asp-route-id="@item.Id">Éditer</a> |
						<a asp-action="Details" asp-route-id="@item.Id">Détails</a> |
						<a asp-action="Delete" asp-route-id="@item.Id">Supprimer</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
	<div>
		<a asp-controller="Administration" asp-action="Index">Retour à l'accueil d'administration</a>
	</div>
</div>